project:
  name: "Wind MVP - Iran Market (IRENEX)"
  years: 10
  currency: "IRR"
  irr_per_usd: 1000000
  discount_rate: 0.12

plant:
  capacity_mw: 20.0
  availability: 0.97
  losses_fraction: 0.10
  degradation_per_year: 0.007

costs:
  capex_usd_per_kw: 1154
  opex_usd_per_kw_yr: 43
  inflation_opex: 0.20
  debt_ratio: 1.0
  loan_rate: 0.18

price:
  iran_daily_path: "C:\\HDD\\Backup\\uni\\Project\\WindPowerPlantAnalysis\\Datasets\\Iran Energy Price Datasets\\آمار_بازار_عمده_فروشی_و_مصرف_کنندگان_بزرگ_برق-بورس_انرژی.xlsx"
  use_vwap: true
  fallback_price_irr_per_mwh: 20000000

  volatility:
    sampler: "bootstrap"      # bootstrap | student_t
    by_bucket: "month_of_year"   # month_of_year | season3 | none
    scale: 1.0
    calibrate_sigma:
      target_monthly_sigma: null   # e.g. 0.18 for σ calibration
      hard_min: 0.5
      hard_max: 2.0
    student_t:
      nu: 5.0

  inflation:
    scenario: baseline          # baseline | piecewise | custom_path
    pass_through: 1.0
    baseline:
      annual_rate: 0.35
    # piecewise:
    #   - months: 24
    #     annual_rate: 0.40
    #   - months: 36
    #     annual_rate: 0.25
    # custom_path:
    #   monthly_rates: []

monte_carlo:
  iterations: 10000
  random_seed: 42
  cf_mean: 0.35
  cf_std: 0.05
  cf_min: 0.05
  cf_max: 0.60

wind:
  scada_path: "C:\\HDD\\Backup\\uni\\Project\\WindPowerPlantAnalysis\\Datasets\\wind turbine scada dataset\\T1.csv"
  forecasting_path: "C:\\HDD\\Backup\\uni\\Project\\WindPowerPlantAnalysis\\Datasets\\wind power forecasting\\Turbine_Data.csv"

  # --- NEW: flexibility ---
  power_curve_source: "theoretical"   # "lowess" | "theoretical" | "auto"
  prefer_source: "auto"               # auto | scada | forecasting

  rated_kw: null
  use_theoretical_power: true

  # calibration knobs
  cf_calibration: 1.2
  fallback_if_mean_cf_below: 0.15

  scada_filters:
    ws_min: 0.0
    ws_max: 35.0
    p_min_kw: 0.0
    p_max_kw: null

  weibull:
    fit_loc_zero: true
    min_points_per_month: 200

  simulate_month_cf:
    reps: 5000
    samples_per_month: 720

  cf_floor: 0.02
  cf_cap: 0.65

  fallback_cf:
    mean: 0.35
    std: 0.05
    min: 0.10
    max: 0.55
