wind:
  mode: scada_calibrated
  city: Tabriz
  weibull_csv_path: C:\HDD\Backup\uni\Project\WindPowerPlantAnalysis\Datasets\weibull_monthly.csv
  hub_height_m: 100
  alpha: 0.14
  power_curve_source: windpowerlib
  turbine_name: E-101/3050
  diurnal_enable: true
  ar1_phi: 0.85
  samples_per_month: 720
scada:
  calibration_profile_path: C:\HDD\Backup\uni\Project\WindPowerPlantAnalysis\Datasets\calibration_profile.json
forecasting:
  enabled: true
  file: C:\HDD\Backup\uni\Project\WindPowerPlantAnalysis\Datasets\wind power forecasting\Turbine_Data.csv
  timestamp_col: 'Unnamed: 0'
  value_pref:
  - WindSpeed
  - ActivePower
  learn_diurnal_factor: true
  by_month: true
  freq: H
  min_days_per_month: 5
  smooth_hours: 3
plant:
  capacity_mw: 20.0
  adjustment_factor: 0.95
project:
  start_year: 2010
  start_month: 1
  years: 10
  discount_rate: 0.12
  n_scenarios: 2000
  n_workers: 1
report:
  title: Wind MVP — Economic Report (USD)
costs:
  capex_usd_per_kw: 900
  opex_usd_per_kw_yr: 35
  inflation_opex: 0.2
monte_carlo:
  iterations: 2000
  random_seed: 4
price:
  us_csv: C:\HDD\Backup\uni\Project\Datasets\Price\U.S. Electricity Prices\clean_data.csv
  unit_source: cent_per_kwh
  state: '*'
  sector: '*'
  weight_col: sales
  tz: UTC
  block_len: 12
optimization:
  enable: false
  min_mw: 5
  max_mw: 50
  step_mw: 5
  objective: NPV_P50
site:
  city: Khaf
economics:
  capex_usd_per_kw: 1000.0
  opex_usd_per_kw_yr: 40.0
  inflation_opex: 0.2
turbine:
  source: windpowerlib
  name: V112/3000
  iec_class: IIA
